apiVersion: v1
kind: Pod
metadata:
  namespace: aap
  labels:
    ansible_job: ''
spec:
  serviceAccountName: default
  automountServiceAccountToken: false
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: disktype
                operator: In
                values:
                  - hdd
  containers:
    - image: >-
        registry.redhat.io/ansible-automation-platform-25/ee-supported-rhel8@sha256:9861e113289cb88696fdefad64b00e9f73af1ea2d241ec161027def3a9ee5be8
      name: worker
      args:
        - ansible-runner
        - worker
        - '--private-data-dir=/runner'
      resources:
        requests:
          cpu: 250m
          memory: 100Mi
